version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Tao moi truong ao va cap nhat pip, setuptools, wheel..."
      - python -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip setuptools wheel
      - echo "Cai dat Cython de ho tro bien dich PyYAML..."
      - pip install "Cython<3.0" pyyaml==6.0.1
      - echo "Dang cai dat cfn-lint va taskcat..."
      - pip install cfn-lint taskcat
  pre_build:
    commands:
      - echo "Kiem tra cu phap CloudFormation bang cfn-lint..."
      - . venv/bin/activate
      - cfn-lint cloudformation/templates/network.yaml
  build:
    commands:
      - echo "Chay Taskcat de test qua trinh tao stack tren AWS..."
      - . venv/bin/activate
      - taskcat test run
  post_build:
    commands:
      - echo "Kiem tra hoan tat!"